# SPDX-License-Identifier: MIT
# Copyright (c) 2022 University of California, Riverside

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: kn-frontend
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "1"
    spec:
      containerConcurrency: 32
      containers:
      - image: shixiongqi/kn-frontend:v1.0.0
        name: kn-frontend
        ports:
        - containerPort: 8080
        # readinessProbe:
        #   initialDelaySeconds: 10
        #   httpGet:
        #     path: "/_healthz"
        #     port: 8080
        #     httpHeaders:
        #     - name: "Cookie"
        #       value: "shop_session-id=x-readiness-probe"
        # livenessProbe:
        #   initialDelaySeconds: 10
        #   httpGet:
        #     path: "/_healthz"
        #     port: 8080
        #     httpHeaders:
        #     - name: "Cookie"
        #       value: "shop_session-id=x-liveness-probe"
        env:
        # - name: PORT
        #   value: "8080"
        - name: PRODUCT_CATALOG_SERVICE_ADDR
          value: "INGRESS_IP:INGRESS_PORT"
        - name: CURRENCY_SERVICE_ADDR
          value: "INGRESS_IP:INGRESS_PORT"
        - name: CART_SERVICE_ADDR
          value: "INGRESS_IP:INGRESS_PORT"
        - name: RECOMMENDATION_SERVICE_ADDR
          value: "INGRESS_IP:INGRESS_PORT"
        - name: SHIPPING_SERVICE_ADDR
          value: "INGRESS_IP:INGRESS_PORT"
        - name: CHECKOUT_SERVICE_ADDR
          value: "INGRESS_IP:INGRESS_PORT"
        - name: AD_SERVICE_ADDR
          value: "INGRESS_IP:INGRESS_PORT"
        - name: PRODUCT_CATALOG_SERVICE_URL
          value: "kn-productcatalogservice.default.example.com"
        - name: CURRENCY_SERVICE_URL
          value: "kn-currencyservice.default.example.com"
        - name: CART_SERVICE_URL
          value: "kn-cartservice.default.example.com"
        - name: RECOMMENDATION_SERVICE_URL
          value: "kn-recommendationservice.default.example.com"
        - name: SHIPPING_SERVICE_URL
          value: "kn-shippingservice.default.example.com"
        - name: CHECKOUT_SERVICE_URL
          value: "kn-checkoutservice.default.example.com"
        - name: AD_SERVICE_URL
          value: "kn-adservice.default.example.com"
        # # ENV_PLATFORM: One of: local, gcp, aws, azure, onprem, alibaba
        # # When not set, defaults to "local" unless running in GKE, otherwies auto-sets to gcp 
        # - name: ENV_PLATFORM 
        #   value: "aws"
        - name: DISABLE_TRACING
          value: "1"
        - name: DISABLE_PROFILER
          value: "1"
        - name: DISABLE_STATS
          value: "1"
        # - name: JAEGER_SERVICE_ADDR
        #   value: "jaeger-collector:14268"
        # - name: CYMBAL_BRANDING
        #   value: "true"
        # resources:
        #   requests:
        #     cpu: 100m
        #     memory: 64Mi
        #   limits:
        #     cpu: 200m
        #     memory: 128Mi
