# SPDX-License-Identifier: MIT
# Copyright (c) 2022 University of California, Riverside

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: kn-recommendationservice
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "1"
    spec:
      containerConcurrency: 32
      containers:
      - image: shixiongqi/kn-recommendationservice:v1.0.0
        name: kn-recommendationservice
        ports:
        - name: h2c
          containerPort: 8080
        readinessProbe:
          periodSeconds: 5
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:8080"]
        livenessProbe:
          periodSeconds: 5
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:8080"]
        env:
        # - name: PORT
        #   value: "8080"
        - name: PRODUCT_CATALOG_SERVICE_ADDR
          value: "INGRESS_IP:INGRESS_PORT"
        - name: PRODUCT_CATALOG_SERVICE_URL
          value: "kn-productcatalogservice.default.example.com"
        - name: DISABLE_TRACING
          value: "1"
        - name: DISABLE_PROFILER
          value: "1"
        - name: DISABLE_DEBUGGER
          value: "1"
        - name: DISABLE_STATS
          value: "1"
        # resources:
        #   requests:
        #     cpu: 100m
        #     memory: 220Mi
        #   limits:
        #     cpu: 200m
        #     memory: 450Mi
