apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: sensor-1
  namespace: default
spec:
  template:
    metadata:
      annotations:
#         autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/metric: rps # concurrency
        autoscaling.knative.dev/target: "1"
        autoscaling.knative.dev/maxScale: "1"
    spec:
      containerConcurrency: 32
      containers:
      - image: docker.io/shixiongqi/kn-dummy
        env:
        - name: SLEEP_TIME
          value: "1000"
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: actuator-2
  namespace: default
spec:
  template:
    metadata:
      annotations:
#         autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/metric: rps # concurrency
        autoscaling.knative.dev/target: "1"
        autoscaling.knative.dev/maxScale: "1"
    spec:
      containerConcurrency: 32
      containers:
      - image: docker.io/shixiongqi/kn-dummy
        env:
        - name: SLEEP_TIME
          value: "1000"